#+title: ROCC-Schema: Romanian Old Cyrillic Corpus schema
#+author: Echipa DeLORo
#+description: Schema de adnotare pentru ROCC.
#+language: ro
#+select_tags: export
#+exclude_tags: noexport
#+options: author:t broken-links:nil c:nil creator:nil
#+options: timestamp:nil title:t toc:t todo:t |:t
#+options: d:(not "LOGBOOK") date:nil e:t email:nil f:t inline:t num:nil
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+setupfile: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+html_mathjax: align: left indent: 5em tagside: left font: Neo-Euler
#+export_file_name: ../index.html
* Standardul intern al corpusului ROCC
  :PROPERTIES:
  :CUSTOM_ID: intro
  :END:
  Corpusul ROCC este format dintr-o mulțime de documente (colecții de pagini), fiecare colecție de acest gen având în componența sa:
  - o secțiune care descrie metadatele colecției: =<pageCollectionMetadata/>=,
  - o secțiune dedicată imaginilor de pagină: =<imagesOfPages/>=,
  - o secțiune dedicată segmentărilor făcute deopotrivă de adnotatori și de tehnologie asupra paginilor: =<segmentationOfImages>=,
  - o secțiune dedicată textelor în alfabet latin care decodifică înscrisul chirilic: =<textsOfPages>=,
  - o secțiune dedicată alinierilor între imagini și text; propunem două variante:
    - una în care alinierile sunt în perechi slovă-la-literă --- =<letterAlignmentsImage2Text>=
    - una în care ele sunt prezentate ca perechi de sevențențe de slove la secvențe de litere, =<seqAlignmentsImage2Text>=.

  În conformitate cu această structurare, o pagină din conținutul unui document se înregistrează în ROCC prin următoarele componente:
  - metadatele atașate paginii (obligatoriu),
  - imaginea propriu-zisă (obligatoriu),
  - segmentările imaginii (opțional),
  - textul transcris (opțional),
  - alinierile imagine-text (opțional).

* Descrierea schemei de adnotare
  :PROPERTIES:
  :CUSTOM_ID: schema
  :END:
** ROCC
   :PROPERTIES:
   :CUSTOM_ID: rocc
   :END:
   Elementul rădăcină al schemei.
** pageCollection
   :PROPERTIES:
   :CUSTOM_ID: pageCollection
   :END:
   La nivelul cel mai de sus al corpusului ROCC se plasează elementele =<pageCollection>=. O astfel de colecție de pagini caracterizează un document, adică o carte, un număr de ziar, în general o unitate editorială ce are asociată un cod de identificare de bibliotecă. La nivelul metadatelor, această descriere combină informații preluate din site-urile bibliotecilor deținătoare de documente vechi românești, cu altele validate și completate apoi în discuțiile purtate între membrii consorțiului DeLORo.

   Este în interesul proiectului ca imaginile scanate ale paginilor chirilice să fie prezentate în corpus în pereche cu transcrierile lor textuale romane. Unitatea de bază în alinierea imagine-text este pagina de carte, dar subîntinderi ale ei vor fi de asemenea considerate: coloana, rândul, cuvântul, litera etc.
** pageCollectionMetadata
   :PROPERTIES:
   :CUSTOM_ID: pageCollectionMetadata
   :END:
   Elementul =<pageCollectionMetadata />= are următoarea structură:
   #+begin_src xml
     <pageCollectionMetadata rocc_id="" title="" shortTitle="" language="" metadataCreator="" distribution="">
       <ROCC-code difficultyLevel="2" writingType="Print" annotationLevel="" century="XIX" printingYear="" fiftyYears ="1" zone ="MD,T,W"></ROCC-code>
       <translation originalLanguage="" originalAuthor="" translator="" secTranslator=""></translation>
       <scannedCopy library="" libraryCode=""></scannedCopy>
       <creation author="" secAuthors="" creationYear="">
	 <creationLocation creationProvince="" creationTown=""></creationLocation>
       </creation>
       <publishing>
	 <publishingLocation publishingCountry="" publishingProvince="" publishingTown="" publishingHouse=""></publishingLocation>
	 <publishingYear></publishingYear>
       </publishing>
       <description style="" subject=""></description>
     </pageCollectionMetadata>
   #+end_src
*** Atribute
    :PROPERTIES:
    :CUSTOM_ID: pageCollectionMetadata-attr
    :END:
    - =rocc_id= (obligatoriu): identificatorul unic al documentului din corpusul =ROCC=;
    - =title= (obligatoriu): itlul documentului (carte, ziar etc.);
    - =shortTitle= (opțional): dacă documentul este cunoscut și sub un nume prescurtat (acest atribut corespunde câmpului UniTitle din codificarea Alef);
    - =language= (obligatoriu): limba sau limbile folosite în document: “ro”, “sl” etc.;
    - =metadataCreator= (obligatoriu): entitatea, una sau mai multe (persoane, instituții) care a editat metadatele colecției curente;
    - =distribution= (obligatoriu): regimul de distribuție al acestei colecției ROCC, valorile fiind tipuri de licențe (ex. https://creativecommons.org/licenses/by-nc/3.0/).
** ROCC-code
   :PROPERTIES:
   :CUSTOM_ID: rocc-code
   :END:
   #+begin_src xml
     <ROCC-code
	 difficultyLevel="2"
	 writingType="Print"
	 annotationLevel=""
	 century="XIX"
	 printingYear="1812"
	 fiftyYears ="1"
	 zone ="MD,T,W" />
   #+end_src
*** Atribute
    :PROPERTIES:
    :CUSTOM_ID: rocc-code-attr
    :END:
    - =difficultyLevel= (obligatoriu): codifică nivelul global de dificultate al colecției de pagini, cu valorile:
      - 1 = ușor,
      - 2 = mediu,
      - 3 = dificil.
    - =writingType= (obligatoriu): completat manual, codifică tipul de scris, cu valorile:
      - =Print= = tipăritură,
      - =Uncial= = manuscris uncial,
      - =Manuscript= = manuscris cu ligaturi între litere.
    - =annotationLevel= (obligatoriu): codifică nivelul de adnotare, cu valorile:
      - =Original= = original, neadnotat;
      - =Gold= = adnotat (parțial sau în totalitate) de experți;
      - =Test= = adnotat de mașină;
      - =Mixt= = adnotat atât manual cât și de mașină (obiecte și transcriere).
      La includerea în ROCC, acest indicator are valoarea implicită =Original=, apoi va fi modificat. automat.
